version: "3"
services:
  envoy:
    container_name: envoy
    restart: "on-failure"
    image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    ports:
      - 30007:9901
      - 30009:8080
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  web:
    container_name: web
    restart: "on-failure"
    image: nginx:latest
    ports:
      - 30008:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf

  client:
    container_name: client
    restart: "on-failure"
    build:
      context: ./client
    expose:
      - 3000
    volumes:
      - './client:/app'
      - '/app/node_modules'
    environment: 
      - NODE_ENV=development 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  server:
    container_name: server
    restart: "on-failure"
    build:
      context: ./server
    ports:
      - 30010:8082
    stdin_open: true
    tty: true