version: "3"
services:
  envoy:
    container_name: envoy
    restart: "on-failure"
    image: envoyproxy/envoy-dev:0b769f6e299dac9115cba10008ce984d0ebf951a
    ports:
      - ${ENVOY_ADMIN_PORT}:9901
      - ${ENVOY_PORT}:8080
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  web:
    container_name: web
    restart: "on-failure"
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf

  client:
    container_name: client
    restart: "on-failure"
    build:
      context: ./client
      args:
        - SERVER_URL=${SERVER_URL}
        - ENVOY_PORT=${ENVOY_PORT}
    expose:
      - 3000
    volumes:
      - './client:/app'
      - '/app/node_modules'
    environment: 
      - NODE_ENV=development 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  server:
    container_name: server
    restart: "on-failure"
    build:
      context: ./server
    ports:
      - ${SERVER_PORT}:8082
    stdin_open: true
    tty: true